name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13

    - name: Install dependencies
      run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev libgl1-mesa-dev libalut-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev

    - name: Xvfb
      run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & 
    
    - name: Build
      run: env GOOS=windows GOARCH=amd64 go build -o main .
    
    - name: Test
      run: go test ./tests


 

